### ISSUE TITLE
sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [anton-zm/sprint-10#3]
Добрый день.

Отлично:
- Хорошее README
- Полностью реализована проверка на имя
- Полностью реализована проверка на номер телефона

К сожалению работа учитывает не все пункты задания. Необходимо исправить.

**Надо исправить:**
- Не проходит проверку валидный email: `mysite@you.me.net`
- Проходит валидацию такой невалидный почтовый ящик `mysite123@gmail.b` (tld не может быть однобуквенным) или `mysite123@gmail.32` (tld не может состоять из цифр)
- Проходит валидацию такой невалиднaй IP-адрес: `http://www.255.255.255.255`, `http://255.255.245.0356`; В ip-адресе должно быть ровно 4 группы, допустимые значения каждой группы от 0 до 255.
- Проходит url с портом: `https://mysite.ru:80000000`. Согласно заданию: `порт — тоже необязательная группа. Порт начинается с двоеточия, за которым идут **от 2 до 5 цифр**`
Также стоит учесть, что из определения максимальный существующий порт - 65535, а все что больше - невалидный.
- Не проходит 2х-цифренный порт: `http://mysite.ru:80`

После исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на github.io.

Работу смогу принять только после устранения всех замечаний из пункта Надо исправить.

**Comment by mrprovoker** [comment]
Спасибо за правки. Теперь работа отличная.

Все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

**Comment by anton-zm** [comment]
Спасибо за ревью!
